import { Customer, InventoryItem, Order } from "@/types/types";

export const sampleCustomers: Omit<
  Customer,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Rajesh Kumar",
    phone: "+91 98765 43210",
    email: "rajesh.k@email.com",
    location: "Connaught Place, Delhi",
    lastVisit: "2024-01-20",
    totalOrders: 5,
    status: "vip",
    prescription: {
      leftEye: "-2.50 -0.75 x 90",
      rightEye: "-2.25 -0.50 x 85",
      pd: "62mm",
      notes: "Prefers progressive lenses",
    },
  },
  {
    name: "Priya Sharma",
    phone: "+91 87654 32109",
    location: "Karol Bagh, Delhi",
    lastVisit: "2024-01-18",
    totalOrders: 2,
    status: "active",
    prescription: {
      leftEye: "+1.75 -0.25 x 180",
      rightEye: "+1.50 -0.50 x 175",
      pd: "58mm",
      notes: "Blue cut coating preferred",
    },
  },
  {
    name: "Amit Singh",
    phone: "+91 76543 21098",
    email: "amit.singh@email.com",
    location: "Lajpat Nagar, Delhi",
    lastVisit: "2024-01-15",
    totalOrders: 8,
    status: "vip",
    prescription: {
      leftEye: "-3.00 -1.00 x 45",
      rightEye: "-2.75 -0.75 x 40",
      pd: "64mm",
      notes: "Bifocal lenses required",
    },
  },
  {
    name: "Meera Patel",
    phone: "+91 65432 10987",
    location: "CP Metro Station, Delhi",
    lastVisit: "2024-01-10",
    totalOrders: 1,
    status: "active",
    prescription: {
      leftEye: "-1.50",
      rightEye: "-1.25",
      pd: "60mm",
      notes: "Single vision, scratch resistant",
    },
  },
  {
    name: "Vikram Malhotra",
    phone: "+91 54321 09876",
    email: "vikram.m@email.com",
    location: "South Extension, Delhi",
    lastVisit: "2024-01-22",
    totalOrders: 3,
    status: "active",
    prescription: {
      leftEye: "+2.00 -0.75 x 90",
      rightEye: "+1.75 -0.50 x 85",
      pd: "61mm",
      notes: "Anti-glare coating",
    },
  },
];

export const sampleInventory: Omit<
  InventoryItem,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    itemCode: "RB-2140-BLK-54",
    brand: "Ray-Ban",
    model: "RB2140 Wayfarer",
    category: "frame",
    type: "Full Rim",
    color: "Black",
    size: "54mm",
    costPrice: 4500,
    sellingPrice: 6500,
    currentStock: 15,
    reorderLevel: 10,
    supplier: "Luxottica India",
    lastRestocked: "2024-01-15",
  },
  {
    itemCode: "ESS-PROG-156",
    brand: "Essilor",
    model: "Varilux Progressive",
    category: "lens",
    type: "Progressive",
    costPrice: 2800,
    sellingPrice: 4200,
    currentStock: 8,
    reorderLevel: 12,
    supplier: "Essilor India",
    lastRestocked: "2024-01-10",
  },
  {
    itemCode: "OAK-8156-SIL-56",
    brand: "Oakley",
    model: "OX8156",
    category: "frame",
    type: "Full Rim",
    color: "Silver",
    size: "56mm",
    costPrice: 3200,
    sellingPrice: 4800,
    currentStock: 22,
    reorderLevel: 15,
    supplier: "Luxottica India",
    lastRestocked: "2024-01-18",
  },
  {
    itemCode: "CASE-HARD-BLK",
    brand: "Generic",
    model: "Hard Case",
    category: "accessory",
    type: "Protective Case",
    color: "Black",
    costPrice: 150,
    sellingPrice: 300,
    currentStock: 45,
    reorderLevel: 20,
    supplier: "Local Supplier",
    lastRestocked: "2024-01-20",
  },
  {
    itemCode: "TITAN-1234-BRN-52",
    brand: "Titan",
    model: "1234",
    category: "frame",
    type: "Full Rim",
    color: "Brown",
    size: "52mm",
    costPrice: 1800,
    sellingPrice: 2800,
    currentStock: 12,
    reorderLevel: 8,
    supplier: "Titan Company",
    lastRestocked: "2024-01-12",
  },
  {
    itemCode: "LENS-SINGLE-BLUE",
    brand: "Essilor",
    model: "Crizal Blue",
    category: "lens",
    type: "Single Vision",
    costPrice: 1200,
    sellingPrice: 1800,
    currentStock: 25,
    reorderLevel: 15,
    supplier: "Essilor India",
    lastRestocked: "2024-01-08",
  },
];

export const sampleOrders: Omit<
  Order,
  "id" | "orderId" | "createdAt" | "updatedAt"
>[] = [
  {
    customerId: "sample-customer-1",
    customerName: "Rajesh Kumar",
    customerPhone: "+91 98765 43210",
    status: "in-lab",
    orderDate: "2024-01-20",
    expectedDelivery: "2024-01-25",
    frameDetails: "Ray-Ban RB2140 - Black",
    lensType: "Progressive - Crizal Coating",
    totalAmount: 8500,
    advancePaid: 5000,
    balanceDue: 3500,
    prescription: {
      leftEye: "-2.50 -0.75 x 90",
      rightEye: "-2.25 -0.50 x 85",
      pd: "62mm",
      notes: "Prefers progressive lenses",
    },
  },
  {
    customerId: "sample-customer-2",
    customerName: "Priya Sharma",
    customerPhone: "+91 87654 32109",
    status: "ready",
    orderDate: "2024-01-18",
    expectedDelivery: "2024-01-23",
    frameDetails: "Oakley OX8156 - Silver",
    lensType: "Single Vision - Blue Cut",
    totalAmount: 6200,
    advancePaid: 6200,
    balanceDue: 0,
    prescription: {
      leftEye: "+1.75 -0.25 x 180",
      rightEye: "+1.50 -0.50 x 175",
      pd: "58mm",
      notes: "Blue cut coating preferred",
    },
  },
  {
    customerId: "sample-customer-3",
    customerName: "Amit Singh",
    customerPhone: "+91 76543 21098",
    status: "pending",
    orderDate: "2024-01-22",
    expectedDelivery: "2024-01-28",
    frameDetails: "Titan 1234 - Brown",
    lensType: "Bifocal - Anti-Glare",
    totalAmount: 4800,
    advancePaid: 2000,
    balanceDue: 2800,
    prescription: {
      leftEye: "-3.00 -1.00 x 45",
      rightEye: "-2.75 -0.75 x 40",
      pd: "64mm",
      notes: "Bifocal lenses required",
    },
  },
  {
    customerId: "sample-customer-4",
    customerName: "Meera Patel",
    customerPhone: "+91 65432 10987",
    status: "delivered",
    orderDate: "2024-01-15",
    expectedDelivery: "2024-01-20",
    frameDetails: "Lenskart LK-5678 - Black",
    lensType: "Single Vision - Scratch Resistant",
    totalAmount: 3200,
    advancePaid: 3200,
    balanceDue: 0,
    prescription: {
      leftEye: "-1.50",
      rightEye: "-1.25",
      pd: "60mm",
      notes: "Single vision, scratch resistant",
    },
  },
  {
    customerId: "sample-customer-5",
    customerName: "Vikram Malhotra",
    customerPhone: "+91 54321 09876",
    status: "confirmed",
    orderDate: "2024-01-21",
    expectedDelivery: "2024-01-26",
    frameDetails: "Ray-Ban RB3025 - Gold",
    lensType: "Progressive - Anti-Glare",
    totalAmount: 7200,
    advancePaid: 4000,
    balanceDue: 3200,
    prescription: {
      leftEye: "+2.00 -0.75 x 90",
      rightEye: "+1.75 -0.50 x 85",
      pd: "61mm",
      notes: "Anti-glare coating",
    },
  },
];
